version: '3.8'
services:
  mysql-employee:
    image: mysql:8.0
    container_name: mysql-employee
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: EmsRoot2024!
      MYSQL_DATABASE: ems_employee_db
    ports:
      - "3309:3306"
    volumes:
      - mysql_employee_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_employee_data: