version: '3.8'
services:
  mysql-performance:
    image: mysql:8.0
    container_name: mysql-performance
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: EmsRoot2024!
      MYSQL_DATABASE: ems_performance_db
    ports:
      - "3310:3306"
    volumes:
      - mysql_performance_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_performance_data: