version: '3.8'
services:
  mysql-email:
    image: mysql:8.0
    container_name: mysql-email
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: EmsRoot2024!
      MYSQL_DATABASE: ems_email_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_email_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_email_data: