version: '3.8'
services:
  mysql-workhour:
    image: mysql:8.0
    container_name: mysql-workhour
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: EmsRoot2024!
      MYSQL_DATABASE: ems_workhour_db
    ports:
      - "3312:3306"
    volumes:
      - mysql_workhour_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_workhour_data:
