version: '3.8'
services:
  mysql-salary:
    image: mysql:8.0
    container_name: mysql-salary
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: EmsRoot2024!
      MYSQL_DATABASE: ems_salary_db
    ports:
      - "3311:3306"
    volumes:
      - mysql_salary_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_salary_data: